// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiToken": string;
      "syncScope": string;
      "selectedGroups": string;
      "syncHighlights": boolean;
      "syncNotes": boolean;
      "colorStrategy": string;
      "autoSyncOnStart": boolean;
      "autoSyncInterval": boolean;
      "syncIntervalMinutes": number;
      "enableBackgroundSync": boolean;
      "enableScheduledSync": boolean;
      "syncOnStartup": boolean;
      "listenToAnnotations": boolean;
      "listenToItems": boolean;
      "annotationDebounceDelay": number;
      "minSyncInterval": number;
      "minItemsToTriggerSync": number;
      "batchSize": number;
      "rateLimit": number;
    };
  }
}
